# Azure DevOps pipeline to build, check source codes, run tests, and more.
#
# This pipeline has been implemented to be run on hosted agent pools based both
# on 'windows' and 'ubuntu' virtual machine images and using the scripts defined
# in the package.json file. Since we are deploying on Azure functions on Windows
# runtime, the pipeline is currently configured to use a Windows hosted image.

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: 'windows-2019'

stages:
  # D) Deploy to a slot 
  - stage: Deploy_staging
    dependsOn: []
    jobs:
      - job: deploy
        steps:

        - task: AzureFunctionApp@1
          inputs:
            azureSubscription: 'Versione di valutazione gratuita(909e9301-d388-4277-947c-277b65681859)'
            appType: 'functionApp'
            appName: 'myfunct71'
            deployToSlotOrASE: true
            resourceGroupName: 'myResourceGroup'
            slotName: 'production'
            package: '$(System.DefaultWorkingDirectory)/'
            deploymentMethod: 'auto'